name: Generate Snake Game from GitHub Contributions

on:
  schedule: # Trigger every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Manually trigger the workflow

permissions:
  contents: write  # Write permissions for the GITHUB_TOKEN

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate Snake Animation from GitHub contributions
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Use your GitHub username
          # Correctly define output files
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git init  # Initialize the Git repository in the workspace
          git remote add origin https://github.com/${{ github.repository }}.git  # Add the remote repository

      # Step 3: Commit the generated files
      - name: Commit generated files
        run: |
          git checkout -b gh-pages || git checkout gh-pages
          git add dist/*
          git commit -m "Add new snake animation"
          # Authenticate and push to the gh-pages branch using GITHUB_TOKEN
          git push https://github.com/${{ github.repository }}.git gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
