name: Generate Snake Game from GitHub Contributions

on:
  schedule: # Trigger every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Manually trigger the workflow

permissions:
  contents: write  # Write permissions for the GITHUB_TOKEN

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate Snake Animation from GitHub contributions
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Use your GitHub username
          # Correctly define output files
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 2: Commit the generated files to the gh-pages branch
      - name: Commit generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git checkout -b gh-pages || git checkout gh-pages
          git add dist/*
          git commit -m "Add new snake animation"
          git push origin HEAD:gh-pages  # Push the files to the 'gh-pages' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
