name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Step 1: Create dist directory
      - name: Create dist directory
        run: mkdir -p dist

      # Step 2: Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: itsZORAL1
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 3: Verify the contents of the directory
      - name: List contents of the directory
        run: ls -R

      # Step 4: Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
