name: Generate Snake Game from GitHub Contributions

on:
  schedule: # Run the workflow every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Use your GitHub username
          # Specify the output file paths directly in the 'outputs' parameter
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 2: Commit the generated files to a specific branch (for example, 'gh-pages')
      - name: Commit generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add dist/*
          git commit -m "Add new snake animation"
          git push origin HEAD:gh-pages  # Push the files to the 'gh-pages' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
